name = "keccak256-composer-action"
main = "workers-site/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./public"

[observability]
enabled = true

[vars]
UPSTASH_REDIS_REST_URL = "https://devoted-zebra-55925.upstash.io"
YOGA_WHISTLES_ENDPOINT = "https://whistles.artlu.xyz/graphql"
